# /.github/workflows/daily.yml
on:
  release:
  #schedule:
    #- cron:  '*/5 * * * *' # every 5 minutes
name: Update
jobs:
  build:
    name: Update data periodically
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/checkout@master
    - name: Build
      run: pip install -r "requirements.txt"
    - name: Update rates
      run: python main.py
      env:
        API_key: ${{ secrets.API_key }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
